# Generated by Django 4.2.11 on 2025-08-09 23:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topics', models.JSONField(default=list)),
                ('info_queries', models.JSONField(default=list)),
                ('direct_urls', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('searching', 'Searching'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='initiated', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=500)),
                ('authors', models.JSONField(default=list)),
                ('harvard_reference', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('no_relevant_info', 'No Relevant Information'), ('error', 'Error')], default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='core.researchsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('page_number', models.IntegerField(default=1)),
                ('note_type', models.CharField(choices=[('quote', 'Quote'), ('statistic', 'Statistic'), ('methodology', 'Methodology')], default='quote', max_length=50)),
                ('search_criteria', models.TextField(blank=True)),
                ('matches_topic', models.TextField(blank=True)),
                ('inline_citations', models.JSONField(default=list)),
                ('reference_list', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.paper')),
            ],
            options={
                'ordering': ['page_number', 'created_at'],
            },
        ),
    ]
