# Generated by Django 4.2.11 on 2025-11-15 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topics', models.JSONField(default=list)),
                ('info_queries', models.JSONField(default=list)),
                ('direct_urls', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('searching', 'Searching'), ('analyzing', 'Analyzing'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='initiated', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='research_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=500)),
                ('authors', models.JSONField(default=list)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('harvard_reference', models.TextField(blank=True)),
                ('total_pages', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('no_relevant_info', 'No Relevant Information'), ('error', 'Error')], default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papers', to='core.researchsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('page_number', models.IntegerField(default=1)),
                ('note_type', models.CharField(choices=[('quote', 'Quote'), ('statistic', 'Statistic'), ('methodology', 'Methodology')], default='quote', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('kept', 'Kept'), ('discarded', 'Discarded')], default='pending', max_length=20)),
                ('search_criteria', models.TextField(blank=True)),
                ('matches_topic', models.TextField(blank=True)),
                ('justification', models.TextField(blank=True)),
                ('inline_citations', models.JSONField(default=list)),
                ('reference_list', models.JSONField(default=dict)),
                ('flagged', models.BooleanField(default=False)),
                ('favorite', models.BooleanField(default=False)),
                ('user_annotations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='notes', to='core.group')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='core.paper')),
                ('projects', models.ManyToManyField(blank=True, related_name='notes', to='core.project')),
                ('sections', models.ManyToManyField(blank=True, related_name='notes', to='core.section')),
            ],
            options={
                'ordering': ['page_number', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_groups', to='core.project'),
        ),
        migrations.AddField(
            model_name='group',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.section'),
        ),
        migrations.AddField(
            model_name='group',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['user'], name='core_sectio_user_id_afd737_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['project'], name='core_sectio_project_cf9c62_idx'),
        ),
        migrations.AddIndex(
            model_name='researchsession',
            index=models.Index(fields=['user'], name='core_resear_user_id_db2904_idx'),
        ),
        migrations.AddIndex(
            model_name='researchsession',
            index=models.Index(fields=['status'], name='core_resear_status_fecc07_idx'),
        ),
        migrations.AddIndex(
            model_name='researchsession',
            index=models.Index(fields=['created_at'], name='core_resear_created_cea7d9_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['user'], name='core_projec_user_id_7e2d66_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['created_at'], name='core_projec_created_1f5557_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['session'], name='core_paper_session_cd0ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['status'], name='core_paper_status_9f42c2_idx'),
        ),
        migrations.AddIndex(
            model_name='paper',
            index=models.Index(fields=['created_at'], name='core_paper_created_898537_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['paper'], name='core_note_paper_i_1a9b04_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['note_type'], name='core_note_note_ty_23f892_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['status'], name='core_note_status_4b8c5c_idx'),
        ),
        migrations.AddIndex(
            model_name='note',
            index=models.Index(fields=['created_at'], name='core_note_created_3e1589_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['user'], name='core_group_user_id_93c07e_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['section'], name='core_group_section_3eb4f1_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['project'], name='core_group_project_2b7da0_idx'),
        ),
    ]
