# Generated by Django 4.2.11 on 2025-08-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_paper_metadata_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('kept', 'Kept'), ('discarded', 'Discarded')], default='pending', max_length=20),
        ),
    ]
