# Generated by Django 4.2.11 on 2025-11-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_group_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='relevance_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
