# Generated by Django 4.2.11 on 2025-08-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_note_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='justification',
            field=models.TextField(blank=True),
        ),
    ]
