# Generated by Django 4.2.11 on 2025-11-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_note_relevance_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='embedding',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
