# Generated by Django 4.2.11 on 2025-11-27 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_note_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='embedding',
        ),
        migrations.RemoveField(
            model_name='note',
            name='relevance_score',
        ),
    ]
