# Generated by Django 4.2.11 on 2025-08-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_note_justification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchsession',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('searching', 'Searching'), ('analyzing', 'Analyzing'), ('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='initiated', max_length=50),
        ),
    ]
