# Generated by Django 4.2.11 on 2025-11-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField()),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
                ('was_successful', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'login_attempts',
                'ordering': ['-attempt_time'],
                'indexes': [models.Index(fields=['email', 'ip_address'], name='login_attem_email_374346_idx'), models.Index(fields=['attempt_time'], name='login_attem_attempt_a9104a_idx')],
            },
        ),
    ]
